/* Generated by Yosys 0.9+431 (git sha1 86e0c8e, gcc 8.5.0 -fPIC -Os) */

/* keep =  1  */
/* top =  1  */
/* src = "h5p2_h/work_test/TLC.v:1" */
module main(Clock, Reset, E, NL, EL, W);
  /* src = "h5p2_h/work_test/TLC.v:74" */
  wire [2:0] _000_;
  /* src = "h5p2_h/work_test/TLC.v:36" */
  wire [2:0] _001_;
  /* src = "h5p2_h/work_test/TLC.v:36" */
  wire [2:0] _002_;
  /* src = "h5p2_h/work_test/TLC.v:36" */
  wire [2:0] _003_;
  /* src = "h5p2_h/work_test/TLC.v:165" */
  wire _004_;
  /* src = "h5p2_h/work_test/TLC.v:166" */
  wire _005_;
  /* src = "h5p2_h/work_test/TLC.v:167" */
  wire _006_;
  /* src = "h5p2_h/work_test/TLC.v:33" */
  wire _007_;
  /* src = "h5p2_h/work_test/TLC.v:33" */
  wire _008_;
  /* src = "h5p2_h/work_test/TLC.v:39" */
  wire _009_;
  /* src = "h5p2_h/work_test/TLC.v:41" */
  wire _010_;
  /* src = "h5p2_h/work_test/TLC.v:41" */
  wire _011_;
  /* src = "h5p2_h/work_test/TLC.v:41" */
  wire _012_;
  /* src = "h5p2_h/work_test/TLC.v:48" */
  wire _013_;
  /* src = "h5p2_h/work_test/TLC.v:50" */
  wire _014_;
  /* src = "h5p2_h/work_test/TLC.v:50" */
  wire _015_;
  /* src = "h5p2_h/work_test/TLC.v:50" */
  wire _016_;
  /* src = "h5p2_h/work_test/TLC.v:61" */
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [2:0] _032_;
  wire [2:0] _033_;
  wire [2:0] _034_;
  wire [2:0] _035_;
  wire [2:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire [6:0] _043_;
  wire [6:0] _044_;
  wire [6:0] _045_;
  wire [6:0] _046_;
  wire [6:0] _047_;
  wire [6:0] _048_;
  wire [6:0] _049_;
  wire [6:0] _050_;
  wire [6:0] _051_;
  wire [6:0] _052_;
  wire [6:0] _053_;
  wire [6:0] _054_;
  wire [6:0] _055_;
  wire [6:0] _056_;
  wire [6:0] _057_;
  wire [6:0] _058_;
  wire [6:0] _059_;
  wire [6:0] _060_;
  /* src = "h5p2_h/work_test/TLC.v:165" */
  wire _061_;
  /* src = "h5p2_h/work_test/TLC.v:165" */
  wire _062_;
  /* src = "h5p2_h/work_test/TLC.v:166" */
  wire _063_;
  /* src = "h5p2_h/work_test/TLC.v:166" */
  wire _064_;
  /* src = "h5p2_h/work_test/TLC.v:167" */
  wire _065_;
  /* src = "h5p2_h/work_test/TLC.v:167" */
  wire _066_;
  /* src = "h5p2_h/work_test/TLC.v:168" */
  wire _067_;
  /* src = "h5p2_h/work_test/TLC.v:33" */
  wire _068_;
  /* src = "h5p2_h/work_test/TLC.v:33" */
  wire _069_;
  /* src = "h5p2_h/work_test/TLC.v:33" */
  wire _070_;
  /* src = "h5p2_h/work_test/TLC.v:33" */
  wire _071_;
  /* src = "h5p2_h/work_test/TLC.v:41" */
  wire _072_;
  /* src = "h5p2_h/work_test/TLC.v:41" */
  wire _073_;
  /* src = "h5p2_h/work_test/TLC.v:50" */
  wire _074_;
  /* src = "h5p2_h/work_test/TLC.v:50" */
  wire _075_;
  /* src = "h5p2_h/work_test/TLC.v:66" */
  wire _076_;
  /* src = "h5p2_h/work_test/TLC.v:166" */
  wire _077_;
  /* src = "h5p2_h/work_test/TLC.v:39" */
  wire _078_;
  /* src = "h5p2_h/work_test/TLC.v:48" */
  wire _079_;
  /* src = "h5p2_h/work_test/TLC.v:61" */
  wire _080_;
  /* src = "h5p2_h/work_test/TLC.v:61" */
  wire _081_;
  /* src = "h5p2_h/work_test/TLC.v:61" */
  wire _082_;
  /* src = "h5p2_h/work_test/TLC.v:66" */
  wire _083_;
  /* src = "h5p2_h/work_test/TLC.v:66" */
  wire _084_;
  wire [2:0] _085_;
  wire _086_;
  wire [2:0] _087_;
  wire [2:0] _088_;
  wire _089_;
  wire [2:0] _090_;
  wire _091_;
  wire [2:0] _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire [2:0] _099_;
  wire [2:0] _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:217" */
  wire [3:0] _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire [3:0] _133_;
  wire [3:0] _134_;
  wire [3:0] _135_;
  wire [3:0] _136_;
  wire [3:0] _137_;
  wire [3:0] _138_;
  wire [3:0] _139_;
  wire [3:0] _140_;
  wire [3:0] _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  /* src = "h5p2_h/work_test/TLC.v:2" */
  input Clock;
  /* src = "h5p2_h/work_test/TLC.v:4" */
  input E;
  /* src = "h5p2_h/work_test/TLC.v:4" */
  input EL;
  /* src = "h5p2_h/work_test/TLC.v:5" */
  wire [6:0] ELTL;
  /* src = "h5p2_h/work_test/TLC.v:11" */
  wire NC;
  /* src = "h5p2_h/work_test/TLC.v:4" */
  input NL;
  /* src = "h5p2_h/work_test/TLC.v:5" */
  wire [6:0] NLTL;
  /* src = "h5p2_h/work_test/TLC.v:9" */
  wire [2:0] Next_State;
  /* src = "h5p2_h/work_test/TLC.v:3" */
  input Reset;
  /* src = "h5p2_h/work_test/TLC.v:12" */
  wire StartTimer;
  /* init = 3'h0 */
  /* src = "h5p2_h/work_test/TLC.v:8" */
  reg [2:0] State = 3'h0;
  /* init = 4'ha */
  /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:179" */
  reg [3:0] \T.Q  = 4'ha;
  /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:180" */
  wire [3:0] \T.Q_Next ;
  /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:177" */
  wire \T.TimeOut ;
  /* src = "h5p2_h/work_test/TLC.v:4" */
  input W;
  /* src = "h5p2_h/work_test/TLC.v:5" */
  wire [6:0] WTL;
  /* src = "h5p2_h/work_test/TLC.v:164" */
  wire collision;
  assign _004_ = _061_ & /* src = "h5p2_h/work_test/TLC.v:165" */ _062_;
  assign _005_ = _063_ & /* src = "h5p2_h/work_test/TLC.v:166" */ _064_;
  assign _006_ = _065_ & /* src = "h5p2_h/work_test/TLC.v:167" */ _066_;
  assign _007_ = _068_ & /* src = "h5p2_h/work_test/TLC.v:33" */ _069_;
  assign _008_ = _007_ & /* src = "h5p2_h/work_test/TLC.v:33" */ _070_;
  assign NC = _008_ & /* src = "h5p2_h/work_test/TLC.v:33" */ _071_;
  assign _009_ = \T.TimeOut  & /* src = "h5p2_h/work_test/TLC.v:39" */ _078_;
  assign _010_ = \T.TimeOut  & /* src = "h5p2_h/work_test/TLC.v:41" */ EL;
  assign _011_ = _010_ & /* src = "h5p2_h/work_test/TLC.v:41" */ _072_;
  assign _012_ = _011_ & /* src = "h5p2_h/work_test/TLC.v:41" */ _073_;
  assign _013_ = \T.TimeOut  & /* src = "h5p2_h/work_test/TLC.v:48" */ _079_;
  assign _014_ = \T.TimeOut  & /* src = "h5p2_h/work_test/TLC.v:50" */ W;
  assign _015_ = _014_ & /* src = "h5p2_h/work_test/TLC.v:50" */ _074_;
  assign _016_ = _015_ & /* src = "h5p2_h/work_test/TLC.v:50" */ _075_;
  assign _017_ = \T.TimeOut  & /* src = "h5p2_h/work_test/TLC.v:61" */ _082_;
  always @* if (1'h1) assert(_067_);
  assign _023_ = _097_ | _096_;
  assign _024_ = _102_ | _101_;
  assign _025_ = _106_ | _105_;
  assign _026_ = _109_ | _108_;
  assign _027_ = _113_ | _112_;
  assign _028_ = _116_ | _115_;
  assign _029_ = _120_ | _119_;
  assign _030_ = _123_ | _122_;
  assign _031_ = _127_ | _126_;
  assign _018_ = | { _093_, _094_, _095_ };
  assign _019_ = | { _024_, _103_, _104_ };
  assign _020_ = | { _026_, _110_, _111_ };
  assign _021_ = | { _028_, _117_, _118_ };
  assign _022_ = | { _030_, _124_, _125_ };
  assign _032_ = _094_ ? _003_ : 3'h6;
  assign _033_ = _093_ ? _092_ : _032_;
  assign _034_ = _096_ ? 3'h6 : _001_;
  assign _035_ = _098_ ? 3'h2 : _100_;
  assign _036_ = _023_ ? _034_ : _035_;
  assign Next_State = _018_ ? _033_ : _036_;
  assign _037_ = _101_ ? 1'h1 : 1'h0;
  assign _038_ = _103_ ? 1'h1 : 1'h1;
  assign _039_ = _024_ ? _037_ : _038_;
  assign _040_ = _105_ ? 1'h0 : 1'h0;
  assign _041_ = _107_ ? 1'h1 : 1'h0;
  assign _042_ = _025_ ? _040_ : _041_;
  assign StartTimer = _019_ ? _039_ : _042_;
  assign _043_ = _108_ ? 7'h2f : 7'h2f;
  assign _044_ = _110_ ? 7'h2f : 7'h11;
  assign _045_ = _026_ ? _043_ : _044_;
  assign _046_ = _112_ ? 7'h2f : 7'h2f;
  assign _047_ = _114_ ? 7'h11 : 7'h10;
  assign _048_ = _027_ ? _046_ : _047_;
  assign WTL = _020_ ? _045_ : _048_;
  assign _049_ = _115_ ? 7'h11 : 7'h10;
  assign _050_ = _117_ ? 7'h2f : 7'h2f;
  assign _051_ = _028_ ? _049_ : _050_;
  assign _052_ = _119_ ? 7'h2f : 7'h2f;
  assign _053_ = _121_ ? 7'h2f : 7'h2f;
  assign _054_ = _029_ ? _052_ : _053_;
  assign ELTL = _021_ ? _051_ : _054_;
  assign _055_ = _122_ ? 7'h2f : 7'h2f;
  assign _056_ = _124_ ? 7'h11 : 7'h2f;
  assign _057_ = _030_ ? _055_ : _056_;
  assign _058_ = _126_ ? 7'h11 : 7'h10;
  assign _059_ = _128_ ? 7'h2f : 7'h2f;
  assign _060_ = _031_ ? _058_ : _059_;
  assign NLTL = _022_ ? _057_ : _060_;
  assign _061_ = ELTL == /* src = "h5p2_h/work_test/TLC.v:165" */ 7'h10;
  assign _062_ = WTL == /* src = "h5p2_h/work_test/TLC.v:165" */ 7'h10;
  assign _063_ = NLTL == /* src = "h5p2_h/work_test/TLC.v:166" */ 7'h10;
  assign _064_ = ELTL == /* src = "h5p2_h/work_test/TLC.v:166" */ 7'h10;
  assign _065_ = NLTL == /* src = "h5p2_h/work_test/TLC.v:167" */ 7'h10;
  assign _066_ = WTL == /* src = "h5p2_h/work_test/TLC.v:167" */ 7'h10;
  assign _067_ = ~ /* src = "h5p2_h/work_test/TLC.v:168" */ collision;
  assign _068_ = ~ /* src = "h5p2_h/work_test/TLC.v:33" */ E;
  assign _069_ = ~ /* src = "h5p2_h/work_test/TLC.v:33" */ W;
  assign _070_ = ~ /* src = "h5p2_h/work_test/TLC.v:33" */ NL;
  assign _071_ = ~ /* src = "h5p2_h/work_test/TLC.v:33" */ EL;
  assign _072_ = ~ /* src = "h5p2_h/work_test/TLC.v:41" */ NC;
  assign _073_ = ~ /* src = "h5p2_h/work_test/TLC.v:41" */ NL;
  assign _074_ = ~ /* src = "h5p2_h/work_test/TLC.v:50" */ NC;
  assign _075_ = ~ /* src = "h5p2_h/work_test/TLC.v:50" */ EL;
  assign _076_ = ~ /* src = "h5p2_h/work_test/TLC.v:66" */ NL;
  assign _077_ = _004_ | /* src = "h5p2_h/work_test/TLC.v:166" */ _005_;
  assign collision = _077_ | /* src = "h5p2_h/work_test/TLC.v:167" */ _006_;
  assign _078_ = NC | /* src = "h5p2_h/work_test/TLC.v:39" */ NL;
  assign _079_ = NC | /* src = "h5p2_h/work_test/TLC.v:48" */ EL;
  assign _080_ = NC | /* src = "h5p2_h/work_test/TLC.v:61" */ E;
  assign _081_ = _080_ | /* src = "h5p2_h/work_test/TLC.v:61" */ W;
  assign _082_ = _081_ | /* src = "h5p2_h/work_test/TLC.v:61" */ NL;
  assign _083_ = E | /* src = "h5p2_h/work_test/TLC.v:66" */ W;
  assign _084_ = _083_ | /* src = "h5p2_h/work_test/TLC.v:66" */ _076_;
  always @(posedge Clock)
      State <= _000_;
  assign _085_ = _017_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:61" */ 3'h7 : 3'h6;
  assign _003_ = _086_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:61|h5p2_h/work_test/TLC.v:38" */ _085_ : 3'hx;
  assign _086_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:61|h5p2_h/work_test/TLC.v:38" */ 3'h6;
  assign _087_ = _016_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:50" */ 3'h3 : 3'h2;
  assign _088_ = _013_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48" */ 3'hx : _087_;
  assign _002_ = _089_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48|h5p2_h/work_test/TLC.v:38" */ _088_ : 3'hx;
  assign _089_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48|h5p2_h/work_test/TLC.v:38" */ 3'h2;
  assign _090_ = _013_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48" */ 3'h5 : _002_;
  assign _001_ = _091_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48|h5p2_h/work_test/TLC.v:38" */ _090_ : 3'hx;
  assign _091_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48|h5p2_h/work_test/TLC.v:38" */ 3'h2;
  assign _092_ = _084_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:66" */ 3'h0 : 3'h2;
  assign _093_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:66|h5p2_h/work_test/TLC.v:38" */ 3'h7;
  assign _094_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:61|h5p2_h/work_test/TLC.v:38" */ 3'h6;
  assign _095_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:59|h5p2_h/work_test/TLC.v:38" */ 3'h5;
  assign _096_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:57|h5p2_h/work_test/TLC.v:38" */ 3'h4;
  assign _097_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:48|h5p2_h/work_test/TLC.v:38" */ 3'h2;
  assign _098_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:46|h5p2_h/work_test/TLC.v:38" */ 3'h1;
  assign _099_ = _012_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:41" */ 3'h4 : 3'h0;
  assign _100_ = _009_ ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:39" */ 3'h1 : _099_;
  assign _101_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:148|h5p2_h/work_test/TLC.v:83" */ 3'h7;
  assign _102_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:138|h5p2_h/work_test/TLC.v:83" */ 3'h6;
  assign _103_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:129|h5p2_h/work_test/TLC.v:83" */ 3'h5;
  assign _104_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:120|h5p2_h/work_test/TLC.v:83" */ 3'h4;
  assign _105_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:111|h5p2_h/work_test/TLC.v:83" */ 3'h3;
  assign _106_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:102|h5p2_h/work_test/TLC.v:83" */ 3'h2;
  assign _107_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:93|h5p2_h/work_test/TLC.v:83" */ 3'h1;
  assign _108_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:148|h5p2_h/work_test/TLC.v:83" */ 3'h7;
  assign _109_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:138|h5p2_h/work_test/TLC.v:83" */ 3'h6;
  assign _110_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:129|h5p2_h/work_test/TLC.v:83" */ 3'h5;
  assign _111_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:120|h5p2_h/work_test/TLC.v:83" */ 3'h4;
  assign _112_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:111|h5p2_h/work_test/TLC.v:83" */ 3'h3;
  assign _113_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:102|h5p2_h/work_test/TLC.v:83" */ 3'h2;
  assign _114_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:93|h5p2_h/work_test/TLC.v:83" */ 3'h1;
  assign _115_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:148|h5p2_h/work_test/TLC.v:83" */ 3'h7;
  assign _116_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:138|h5p2_h/work_test/TLC.v:83" */ 3'h6;
  assign _117_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:129|h5p2_h/work_test/TLC.v:83" */ 3'h5;
  assign _118_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:120|h5p2_h/work_test/TLC.v:83" */ 3'h4;
  assign _119_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:111|h5p2_h/work_test/TLC.v:83" */ 3'h3;
  assign _120_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:102|h5p2_h/work_test/TLC.v:83" */ 3'h2;
  assign _121_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:93|h5p2_h/work_test/TLC.v:83" */ 3'h1;
  assign _122_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:148|h5p2_h/work_test/TLC.v:83" */ 3'h7;
  assign _123_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:138|h5p2_h/work_test/TLC.v:83" */ 3'h6;
  assign _124_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:129|h5p2_h/work_test/TLC.v:83" */ 3'h5;
  assign _125_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:120|h5p2_h/work_test/TLC.v:83" */ 3'h4;
  assign _126_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:111|h5p2_h/work_test/TLC.v:83" */ 3'h3;
  assign _127_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:102|h5p2_h/work_test/TLC.v:83" */ 3'h2;
  assign _128_ = State == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:93|h5p2_h/work_test/TLC.v:83" */ 3'h1;
  assign _000_ = Reset ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:75" */ 3'h0 : Next_State;
  assign _132_ = _143_ | _142_;
  assign _130_ = | { _147_, _148_, _149_ };
  assign _131_ = | { _132_, _144_, _145_, _146_ };
  assign _133_ = _142_ ? 4'h0 : 4'h0;
  assign _134_ = _145_ ? 4'h2 : 4'h3;
  assign _135_ = _144_ ? 4'h1 : _134_;
  assign _136_ = _132_ ? _133_ : _135_;
  assign _137_ = _148_ ? 4'h5 : 4'h6;
  assign _138_ = _147_ ? 4'h4 : _137_;
  assign _139_ = _151_ ? 4'h8 : 4'h9;
  assign _140_ = _150_ ? 4'h7 : _139_;
  assign _141_ = _130_ ? _138_ : _140_;
  assign \T.Q_Next  = _131_ ? _136_ : _141_;
  assign \T.TimeOut  = \T.Q  == /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:227" */ 4'h0;
  always @(negedge Clock)
      \T.Q  <= _129_;
  assign _129_ = StartTimer ? /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:219" */ 4'h9 : \T.Q_Next ;
  assign _142_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:212" */ 4'h0;
  assign _143_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:211" */ 4'h1;
  assign _144_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:210" */ 4'h2;
  assign _145_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:209" */ 4'h3;
  assign _146_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:208" */ 4'h4;
  assign _147_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:207" */ 4'h5;
  assign _148_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:206" */ 4'h6;
  assign _149_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:205" */ 4'h7;
  assign _150_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:204" */ 4'h8;
  assign _151_ = \T.Q  == /* full_case = 32'd1 */ /* src = "h5p2_h/work_test/TLC.v:159|h5p2_h/work_test/TLC.v:201|h5p2_h/work_test/TLC.v:203" */ 4'h9;
endmodule
